# Generated by Django 4.1 on 2022-08-31 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
