# Generated by Django 4.1 on 2022-08-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
