# Generated by Django 4.1 on 2022-10-21 10:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sessions_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
