# Generated by Django 4.1 on 2022-10-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_header_logo_alter_sessions_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
