# Generated by Django 4.1 on 2022-10-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_sessions_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Schedule',
        ),
    ]
