# Generated by Django 4.1 on 2022-10-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_sessions_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Cabecera', 'verbose_name_plural': 'Cabecera'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Numero de Telefono', 'verbose_name_plural': 'Numeros de Telfono'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Set', 'verbose_name_plural': 'Sets'},
        ),
    ]
