# Generated by Django 4.1 on 2022-10-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_header_options_alter_phonenumber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
