# Generated by Django 4.1 on 2022-10-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_schedule_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='image',
        ),
        migrations.AddField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='image_h',
            field=models.ImageField(blank=True, null=True, upload_to='images/Sessions', verbose_name='Imagen Banner(Si se requiere)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='image_v',
            field=models.ImageField(default=1, upload_to='images/Sessions', verbose_name='Imagen vertical(Portada del Set)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='image_v1',
            field=models.ImageField(default=1, upload_to='images/Sessions', verbose_name='Imagen vertical Foto demostrativa 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='image_v2',
            field=models.ImageField(default=1, upload_to='images/Sessions', verbose_name='Imagen vertical Foto demostrativa 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='image_v3',
            field=models.ImageField(default=1, upload_to='images/Sessions', verbose_name='Imagen vertical Foto demostrativa 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Link Automatico (NO MODIFICAR)'),
        ),
    ]
