# Generated by Django 4.1 on 2022-10-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_schedule_image_schedule_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='header',
            name='number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
