# Generated by Django 4.1 on 2022-10-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_phonenumber_header_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images/general', verbose_name='Imagen que se descargara')),
            ],
            options={
                'verbose_name': 'Imagen negra',
                'verbose_name_plural': 'Imagenes en negro',
            },
        ),
    ]
