# Generated by Django 4.1.3 on 2022-11-12 11:41

import ckeditor.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_author_alter_schedule_image_h_alter_schedule_image_v_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='video',
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_chapter',
            field=models.FileField(default=1, upload_to=core.models.chapter_directory_path, verbose_name='Video del Capitulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='video_course',
            field=models.FileField(default=1, upload_to=core.models.user_directory_path, verbose_name='Video Demo'),
            preserve_default=False,
        ),
    ]
