# Generated by Django 4.1.3 on 2022-11-12 19:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_firs_name_author_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido del curso'),
        ),
        migrations.AddField(
            model_name='courses',
            name='short_des',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion Corta'),
        ),
    ]
