# Generated by Django 4.1.3 on 2022-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_schedule_stripe_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/general', verbose_name='Imagen 1 de animacion')),
                ('image2', models.ImageField(upload_to='images/general', verbose_name='Imagen 2 de animacion')),
                ('image3', models.ImageField(upload_to='images/general', verbose_name='Imagen 3 de animacion')),
            ],
        ),
    ]
