# Generated by Django 4.1.3 on 2022-11-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_imagesanimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesanimation',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
