# Generated by Django 4.1.3 on 2022-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_imagesanimation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesanimation',
            name='logo',
            field=models.ImageField(default=1, upload_to='images/general', verbose_name='Imagen central (Logo)'),
            preserve_default=False,
        ),
    ]
