# Generated by Django 4.1.3 on 2022-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_imagesanimation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesanimation',
            name='image4',
            field=models.ImageField(default=1, upload_to='images/general', verbose_name='Imagen 4 de animacion'),
            preserve_default=False,
        ),
    ]
