# Generated by Django 4.1.3 on 2022-11-30 19:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_imagesanimation_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
