# Generated by Django 4.1.3 on 2022-12-01 11:31

import ckeditor.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_pricing_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image_portada', models.ImageField(upload_to=core.models.works_directory_path, verbose_name='Imagen de Portada')),
                ('short_desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion corta')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
    ]
