# Generated by Django 4.1.3 on 2022-12-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='Link Automatico (NO MODIFICAR)'),
            preserve_default=False,
        ),
    ]
