# Generated by Django 4.1.3 on 2022-11-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perfil_photo',
            field=models.ImageField(default=1, upload_to='images/accounts', verbose_name='Foto de Perfil'),
            preserve_default=False,
        ),
    ]
