# Generated by Django 4.1.3 on 2022-11-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_poins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='poins',
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
